name: Delete Merged Branch

on:
  push:
    branches:
      - main  # Substitua pelo nome da sua branch principal
  pull_request:
    branches:
      - main  # Substitua pelo nome da sua branch principal
  workflow_dispatch:

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge and Delete Branch
        run: |
          # Merge the pull request (if the event is pull_request)
          if [ -n "${{ github.event.pull_request }}" ]; then
            git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
            git merge pr-${{ github.event.pull_request.number }}
            git branch -d pr-${{ github.event.pull_request.number }}
          else
            # Delete the branch after push event
            git branch -d ${{ github.ref }}
            git push origin --delete ${{ github.ref }}
          fi
