name: Delete Merged Branch

on:
  push:
    branches:
      - master  # Substitua pelo nome de sua branch principal

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Branch
        run: |
          git branch -d ${{ github.event.pull_request.head.ref }}
          git push origin --delete ${{ github.event.pull_request.head.ref }}
