name: Delete Branch After Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          git fetch --prune
          git push origin --delete ${{ github.head_ref }}
