name: Unit test and Merge

on:
  push:
    branches:
      - develop
      - main
      - hotfix/*
  pull_request:
    branches:
      - develop
      - main
      - hotfix/*

jobs:
  build-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    - name: Fetch and checkout main
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'hotfix/'))
      run: |
        git fetch origin main
        git checkout main

    - name: Pull latest changes on main
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'hotfix/'))
      run: git pull origin main

    - name: Merge hotfix into main
      if: github.event_name == 'push' && github.ref == 'refs/heads/hotfix/*'
      run: |
        git fetch origin hotfix
        git checkout hotfix
        git pull origin hotfix
        git checkout main
        git merge hotfix
        git push origin main

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Run tests with Maven
      run: mvn test

    - name: Deploy to Production
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Add deployment steps here
